#!/usr/bin/env python3
"""
Generate tests/molecular_orbital_data.hpp from PySCF RHF/cc-pVDZ calculations.
Run: micromamba run -n ltfp python tests/gen_orbital_denominators.py
"""
import os
import numpy as np
from pyscf import gto, scf

MOLECULES = [
    ("ne",
     "Ne 0 0 0",
     0, 0),
    ("h2o",
     "O 0 0 0; H 0 0.757 0.586; H 0 -0.757 0.586",
     0, 0),
    ("nh3",
     "N 0 0 0.116; H 0 0.931 -0.272; H 0.807 -0.465 -0.272; H -0.807 -0.465 -0.272",
     0, 0),
    ("co2",
     "C 0 0 0; O 0 0 1.162; O 0 0 -1.162",
     0, 0),
    ("benzene",
     "C  1.396  0.000  0.000;"
     "C  0.698  1.209  0.000;"
     "C -0.698  1.209  0.000;"
     "C -1.396  0.000  0.000;"
     "C -0.698 -1.209  0.000;"
     "C  0.698 -1.209  0.000;"
     "H  2.481  0.000  0.000;"
     "H  1.241  2.149  0.000;"
     "H -1.241  2.149  0.000;"
     "H -2.481  0.000  0.000;"
     "H -1.241 -2.149  0.000;"
     "H  1.241 -2.149  0.000",
     0, 0),
]


def run_rhf(name, atom, charge, spin):
    mol = gto.Mole()
    mol.atom = atom
    mol.basis = "cc-pvdz"
    mol.charge = charge
    mol.spin = spin
    mol.verbose = 0
    mol.build()
    mf = scf.RHF(mol)
    mf.kernel()
    occ  = np.sort(mf.mo_energy[mf.mo_occ > 0])
    virt = np.sort(mf.mo_energy[mf.mo_occ == 0])
    return occ, virt


def fmt_array(vals):
    items = [f"{v:.20e}" for v in vals]
    rows = []
    for i in range(0, len(items), 4):
        rows.append(", ".join(items[i:i + 4]))
    return "{\n" + ",\n".join("        " + r for r in rows) + "\n    }"


def main():
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "molecular_orbital_data.hpp")
    results = []
    for name, atom, charge, spin in MOLECULES:
        print(f"  Running {name}...", flush=True)
        occ, virt = run_rhf(name, atom, charge, spin)
        results.append((name, occ, virt))
        print(f"    n_occ={len(occ)}, n_virt={len(virt)}", flush=True)

    lines = [
        "// AUTO-GENERATED by tests/gen_orbital_denominators.py -- do not edit.",
        "// Run: micromamba run -n ltfp python tests/gen_orbital_denominators.py",
        "#pragma once",
        "",
        "namespace mol_data {",
        "",
        "struct MoleculeData {",
        "    const char*   name;",
        "    int           n_occ;",
        "    int           n_virt;",
        "    const double* occ;   // sorted ascending, Hartree",
        "    const double* virt;  // sorted ascending, Hartree",
        "};",
        "",
    ]
    for name, occ, virt in results:
        lines.append(f"static constexpr double {name}_occ[]  = {fmt_array(occ)};")
        lines.append(f"static constexpr double {name}_virt[] = {fmt_array(virt)};")
        lines.append("")
    lines.append("static constexpr MoleculeData MOLECULES[] = {")
    for name, occ, virt in results:
        lines.append(f'    {{"{name}", {len(occ)}, {len(virt)}, {name}_occ, {name}_virt}},')
    lines += [
        "};",
        f"static constexpr int N_MOLECULES = {len(results)};",
        "",
        "} // namespace mol_data",
        "",
    ]
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
