#pragma once
#include <iostream>
#include <ostream>
#include <vector>

#ifdef MINIMAX_CPPPY_DEBUG_MODE__
#include <atomic>
namespace minimax_cpppy {
namespace debug {
    // Number of times detail::evalLogErrorDerivatives has been called since last reset.
    // Valid only in Debug builds (MINIMAX_CPPPY_DEBUG_MODE__).
    inline std::atomic<long long> functional1_call_count{0};
    static_assert(std::atomic<long long>::is_always_lock_free,
                  "minimax_cpppy::debug: long long counter must be lock-free");

    inline long long get_functional1_call_count() noexcept {
        return functional1_call_count.load(std::memory_order_relaxed);
    }
    inline void reset_functional1_call_count() noexcept {
        functional1_call_count.store(0, std::memory_order_relaxed);
    }

    // Number of times detail::evalEquioscillation has been called since last reset.
    // Valid only in Debug builds (MINIMAX_CPPPY_DEBUG_MODE__).
    inline std::atomic<long long> eval_equioscillation_call_count{0};

    inline long long get_eval_equioscillation_call_count() noexcept {
        return eval_equioscillation_call_count.load(std::memory_order_relaxed);
    }
    inline void reset_eval_equioscillation_call_count() noexcept {
        eval_equioscillation_call_count.store(0, std::memory_order_relaxed);
    }
} // namespace debug
} // namespace minimax_cpppy
#endif // MINIMAX_CPPPY_DEBUG_MODE__

namespace minimax_cpppy {

struct MinimaxResult {
    std::vector<double> expon;
    std::vector<double> weight;
    double errmax;
};

// Compute MINIMAX-optimal Laplace exponents and weights for 1/x on [ymin, ymax].
// Approximation: 1/x ≈ Σ_k weight[k] * exp(-expon[k] * x) for x ∈ [ymin, ymax].
// Requires: 1 <= nlap <= 30  (dense interpolated ext tables, generated by gen_table)
// Requires: 0 < ymin < ymax.
// Throws std::invalid_argument if nlap or range constraints are violated (Debug builds).
// verbose: 0=none, 1=errors, 2=+warnings, 3=+info per Remez/NR iter, 4=+debug per Newton step.
// Thread safety: all public functions are thread-safe. No mutable global state (debug
//       counters are atomic and compiled out in Release). Safe to call concurrently.
MinimaxResult laplaceMinimax(int nlap, double ymin, double ymax,
                              int verbose = 3,
                              std::ostream& os = std::cerr);

// Overload: provide initial guess in [ymin, ymax] domain; bypasses table lookup.
// init_expon and init_weight must have exactly nlap elements.
// Used by the Python bindings' init_expon/init_weight kwargs (python/_minimax_core.cpp).
MinimaxResult laplaceMinimax(int nlap, double ymin, double ymax,
                              const std::vector<double>& init_expon,
                              const std::vector<double>& init_weight,
                              int verbose = 3,
                              std::ostream& os = std::cerr);

} // namespace minimax_cpppy
