// Extended pre-tabulated MINIMAX initial data: variable-length two-tier
// (cusp-clustered) non-uniform ratio grid per nlap; row counts in EXT_COUNTS.
// Data arrays defined in src/core/data_ext_NN.cpp (NN=01..30, auto-generated by gen_table).
// Regenerate with: cmake -B build_tools -DMINIMAX_CPPPY_BUILD_TOOLS=ON && cmake --build build_tools && ./build_tools/gen_table src/core
#ifndef MINIMAX_CPPPY_MINIMAX_DATA_EXT_HPP
#define MINIMAX_CPPPY_MINIMAX_DATA_EXT_HPP

#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <string>

#include "data_ext_counts.hpp"

namespace minimax_cpppy {
namespace detail {
namespace data {

static constexpr int MAX_NLAP = 30; ///< Maximum nlap covered by the ext tables.

struct ExtTableEntry {
    double range;        ///< ratio = ymax/ymin for this row
    double errmax;       ///< initial error amplitude
    double expon[53];    ///< initial exponents (first nlap valid)
    double weight[53];   ///< initial weights   (first nlap valid)
    double extrema[105]; ///< interior extrema in [1,ratio] (first 2*nlap-1 valid)
};

// One per-nlap extern array (defined in data_ext_NN.cpp, auto-generated by gen_table).
// Unsized: row counts are variable per nlap, given by EXT_COUNTS (data_ext_counts.hpp).
extern const ExtTableEntry EXT_TABLE_01[];
extern const ExtTableEntry EXT_TABLE_02[];
extern const ExtTableEntry EXT_TABLE_03[];
extern const ExtTableEntry EXT_TABLE_04[];
extern const ExtTableEntry EXT_TABLE_05[];
extern const ExtTableEntry EXT_TABLE_06[];
extern const ExtTableEntry EXT_TABLE_07[];
extern const ExtTableEntry EXT_TABLE_08[];
extern const ExtTableEntry EXT_TABLE_09[];
extern const ExtTableEntry EXT_TABLE_10[];
extern const ExtTableEntry EXT_TABLE_11[];
extern const ExtTableEntry EXT_TABLE_12[];
extern const ExtTableEntry EXT_TABLE_13[];
extern const ExtTableEntry EXT_TABLE_14[];
extern const ExtTableEntry EXT_TABLE_15[];
extern const ExtTableEntry EXT_TABLE_16[];
extern const ExtTableEntry EXT_TABLE_17[];
extern const ExtTableEntry EXT_TABLE_18[];
extern const ExtTableEntry EXT_TABLE_19[];
extern const ExtTableEntry EXT_TABLE_20[];
extern const ExtTableEntry EXT_TABLE_21[];
extern const ExtTableEntry EXT_TABLE_22[];
extern const ExtTableEntry EXT_TABLE_23[];
extern const ExtTableEntry EXT_TABLE_24[];
extern const ExtTableEntry EXT_TABLE_25[];
extern const ExtTableEntry EXT_TABLE_26[];
extern const ExtTableEntry EXT_TABLE_27[];
extern const ExtTableEntry EXT_TABLE_28[];
extern const ExtTableEntry EXT_TABLE_29[];
extern const ExtTableEntry EXT_TABLE_30[];

inline const ExtTableEntry* extTableForNlap(int nlap) {
    static const ExtTableEntry* const tables[MAX_NLAP] = {
        EXT_TABLE_01, EXT_TABLE_02, EXT_TABLE_03, EXT_TABLE_04, EXT_TABLE_05,
        EXT_TABLE_06, EXT_TABLE_07, EXT_TABLE_08, EXT_TABLE_09, EXT_TABLE_10,
        EXT_TABLE_11, EXT_TABLE_12, EXT_TABLE_13, EXT_TABLE_14, EXT_TABLE_15,
        EXT_TABLE_16, EXT_TABLE_17, EXT_TABLE_18, EXT_TABLE_19, EXT_TABLE_20,
        EXT_TABLE_21, EXT_TABLE_22, EXT_TABLE_23, EXT_TABLE_24, EXT_TABLE_25,
        EXT_TABLE_26, EXT_TABLE_27, EXT_TABLE_28, EXT_TABLE_29, EXT_TABLE_30,
    };
    return (nlap >= 1 && nlap <= MAX_NLAP) ? tables[nlap - 1] : nullptr;
}

static constexpr int EXT_LAGRANGE_ORDER = 9;

inline int extTableSizeForNlap(int nlap) {
    return (nlap >= 1 && nlap <= MAX_NLAP) ? EXT_COUNTS[nlap - 1] : 0;
}

/**
 * Interpolate an entry from a sorted, non-uniform table using binary-search and
 * local order-N Lagrange interpolation in log10(range) space.
 *
 * Works for any monotonically increasing range[] values. Clamps the target ratio
 * to [tbl[0].range, tbl[count-1].range] before interpolating.
 *
 * @param tbl       Sorted-ascending-by-range ExtTableEntry array
 * @param count     Number of entries in tbl
 * @param nlap      Laplace points; interpolates expon[0..nlap-1], weight[0..nlap-1],
 *                  extrema[0..2*nlap-2], and errmax
 * @param ratio     Target ymax/ymin ratio, clamped to [tbl[0].range, tbl[count-1].range]
 * @param order     Lagrange stencil size (clamped to count; window shrinks/shifts at ends)
 * @return          Interpolated ExtTableEntry with .range = ratio
 */
inline ExtTableEntry interpolateEntries(const ExtTableEntry* tbl, int count,
                                        int nlap, double ratio, int order) {
    const double lo_r = tbl[0].range;
    const double hi_r = tbl[count - 1].range;
    const double clamped = std::max(lo_r, std::min(hi_r, ratio));
    const double lr = std::log10(clamped);

    // Bracket lr between adjacent nodes (log10 of range).
    int a = 0, b = count - 1;
    while (b - a > 1) {
        const int mid = (a + b) / 2;
        if (std::log10(tbl[mid].range) <= lr) a = mid; else b = mid;
    }
    const int center =
        (lr - std::log10(tbl[a].range) <= std::log10(tbl[b].range) - lr) ? a : b;

    const int n = std::min({order, count, 16});  // clamp to xs/L buffer size
    const int half = n / 2;
    const int start = std::max(0, std::min(count - n, center - half));

    double xs[16], L[16];                  // order capped at 16; default 9
    for (int j = 0; j < n; ++j) xs[j] = std::log10(tbl[start + j].range);
    for (int j = 0; j < n; ++j) {
        L[j] = 1.0;
        for (int m = 0; m < n; ++m)
            if (m != j) L[j] *= (lr - xs[m]) / (xs[j] - xs[m]);
    }

    ExtTableEntry result{};
    result.range = ratio;
    const int n_ext = 2 * nlap - 1;
    for (int j = 0; j < n; ++j) {
        const ExtTableEntry& e = tbl[start + j];
        result.errmax += L[j] * e.errmax;
        for (int k = 0; k < nlap; ++k) {
            result.expon[k]  += L[j] * e.expon[k];
            result.weight[k] += L[j] * e.weight[k];
        }
        for (int k = 0; k < n_ext; ++k) result.extrema[k] += L[j] * e.extrema[k];
    }
    return result;
}

/**
 * Delegates to interpolateEntries for nlap's pre-tabulated table at EXT_LAGRANGE_ORDER.
 *
 * @throws std::invalid_argument if nlap is out of [1, MAX_NLAP]
 */
inline ExtTableEntry interpolatedLookup(int nlap, double ratio) {
    if (nlap < 1 || nlap > MAX_NLAP) {
        throw std::invalid_argument(
            "interpolatedLookup: nlap out of [1," + std::to_string(MAX_NLAP) + "]: " + std::to_string(nlap));
    }
    return interpolateEntries(extTableForNlap(nlap), extTableSizeForNlap(nlap),
                              nlap, ratio, EXT_LAGRANGE_ORDER);
}

} // namespace data
} // namespace detail
} // namespace minimax_cpppy

#endif // MINIMAX_CPPPY_MINIMAX_DATA_EXT_HPP
