// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_05 for nlap=5.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_05.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
