// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_21 for nlap=21.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_21.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
