// AUTO-GENERATED by tools/gen_table -- do not edit.
#include "data_ext_counts.hpp"
namespace minimax_cpppy { namespace detail { namespace data {
const int EXT_COUNTS[30] = {106,108,109,109,110,110,111,111,111,111,111,111,111,111,111,136,136,136,136,136,136,136,136,162,162,162,162,162,162,162};
} } }
