// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_11 for nlap=11.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_11.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
