// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_16 for nlap=16.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_16.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
