// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_14 for nlap=14.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_14.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
