// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_13 for nlap=13.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_13.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
