// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_23 for nlap=23.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_23.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
