// Per-nlap ext-table row counts. Regenerated by gen_table (Task 5).
#ifndef MINIMAX_CPPPY_DATA_EXT_COUNTS_HPP
#define MINIMAX_CPPPY_DATA_EXT_COUNTS_HPP
namespace minimax_cpppy { namespace detail { namespace data {
extern const int EXT_COUNTS[30];
} } }
#endif
