// AUTO-GENERATED by tools/gen_table -- do not edit.
// Defines EXT_TABLE_01 for nlap=1.
#include "data_ext.hpp"
namespace minimax_cpppy {
namespace detail {
namespace data {
#include "data_ext_01.hpp"
} // namespace data
} // namespace detail
} // namespace minimax_cpppy
